#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 18 15:34:25 2018

Copyright (c) 2018, University of Oslo
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.
* Neither the name of the HISP project nor the names of its contributors may
  be used to endorse or promote products derived from this software without
  specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE

@author: philld
"""

from dhis2api.genson import SchemaBuilder
import json
from pprint import pprint, pformat
from ast import literal_eval

builder = SchemaBuilder(False)

in_schema = {'items': {'maxProperties': 2147483647,
           'minProperties': 0,
           'properties': {'access': {'maxProperties': 1,
                                     'minProperties': 1,
                                     'properties': {'delete': {'type': 'boolean'},
                                                    'externalize': {'type': 'boolean'},
                                                    'manage': {'type': 'boolean'},
                                                    'read': {'type': 'boolean'},
                                                    'update': {'type': 'boolean'},
                                                    'write': {'type': 'boolean'}},
                                     'readOnly': True,
                                     'type': 'object'},
                          'attributeValue': {'items': {'maxProperties': 2147483647,
                                                       'minProperties': 0,
                                                       'properties': {'attribute': {'format': 'uid',
                                                                                    'maxLength': 11,
                                                                                    'minLength': 11,
                                                                                    'readOnly': False,
                                                                                    'type': 'string'},
                                                                      'created': {'format': 'date-time',
                                                                                  'maxLength': 23,
                                                                                  'minLength': 0,
                                                                                  'readOnly': False,
                                                                                  'type': 'string'},
                                                                      'lastUpdated': {'format': 'date-time',
                                                                                      'maxLength': 23,
                                                                                      'minLength': 0,
                                                                                      'readOnly': False,
                                                                                      'type': 'string'},
                                                                      'value': {'maxLength': 255,
                                                                                'minLength': 0,
                                                                                'readOnly': False,
                                                                                'type': 'string'}},
                                                       'required': []},
                                             'maxItems': 2147483647,
                                             'minItems': 0,
                                             'readOnly': False,
                                             'type': 'array'},
                          'attributeValues': {'maxItems': 2147483647,
                                              'minItems': 0,
                                              'type': 'array'},
                          'categoryAttribute': {'type': 'boolean'},
                          'categoryOptionAttribute': {'type': 'boolean'},
                          'categoryOptionComboAttribute': {'type': 'boolean'},
                          'categoryOptionGroupAttribute': {'type': 'boolean'},
                          'categoryOptionGroupSetAttribute': {'type': 'boolean'},
                          'code': {'example': 'mycode',
                                   'format': 'general',
                                   'maxLength': 50,
                                   'minLength': 1,
                                   'type': 'string',
                                   'unique': 'true'},
                          'constantAttribute': {'type': 'boolean'},
                          'created': {'example': '2015-04-24T12:12:54.407',
                                      'format': 'date-time',
                                      'maxLength': 23,
                                      'minLength': 23,
                                      'type': 'string'},
                          'dataElementAttribute': {'type': 'boolean'},
                          'dataElementGroupAttribute': {'type': 'boolean'},
                          'dataElementGroupSetAttribute': {'type': 'boolean'},
                          'dataSetAttribute': {'type': 'boolean'},
                          'description': {'format': 'general',
                                          'maxLength': 255,
                                          'minLength': 1,
                                          'type': 'string'},
                          'displayDescription': {'format': 'general',
                                                 'maxLength': 255,
                                                 'minLength': 1,
                                                 'type': 'string'},
                          'displayName': {'example': 'mydisplayName',
                                          'format': 'general',
                                          'maxLength': 255,
                                          'minLength': 1,
                                          'type': 'string'},
                          'displayShortName': {'format': 'general',
                                               'maxLength': 255,
                                               'minLength': 1,
                                               'type': 'string'},
                          'documentAttribute': {'type': 'boolean'},
                          'externalAccess': {'type': 'boolean'},
                          'favorite': {'items': {'format': 'general',
                                                 'maxLength': 255,
                                                 'minLength': 1,
                                                 'type': 'string'},
                                       'maxItems': 2147483647,
                                       'minItems': 0,
                                       'readOnly': False,
                                       'type': 'array'},
                          'favorites': {'maxItems': 2147483647,
                                        'minItems': 0,
                                        'type': 'array'},
                          'href': {'example': 'http://localhost:8080/api/attributes/DnrLSdo4hMl',
                                   'format': 'url',
                                   'maxLength': 255,
                                   'minLength': 1,
                                   'type': 'string'},
                          'id': {'example': 'DnrLSdo4hMl',
                                 'format': 'uid',
                                 'maxLength': 11,
                                 'minLength': 11,
                                 'type': 'string',
                                 'unique': 'true'},
                          'indicatorAttribute': {'type': 'boolean'},
                          'indicatorGroupAttribute': {'type': 'boolean'},
                          'lastUpdated': {'example': '2015-04-24T12:12:54.408',
                                          'format': 'date-time',
                                          'maxLength': 23,
                                          'minLength': 23,
                                          'type': 'string'},
                          'lastUpdatedBy': {'association': 'true',
                                            'example': 'GOLswS44mh8',
                                            'format': 'uid',
                                            'maxLength': 11,
                                            'minLength': 11,
                                            'readOnly': 'true',
                                            'type': 'string'},
                          'legendSetAttribute': {'type': 'boolean'},
                          'mandatory': {'type': 'boolean'},
                          'name': {'example': 'myname',
                                   'format': 'general',
                                   'maxLength': 230,
                                   'minLength': 1,
                                   'type': 'string',
                                   'unique': 'true'},
                          'optionAttribute': {'type': 'boolean'},
                          'optionSet': {'association': 'true',
                                        'format': 'uid',
                                        'maxLength': 11,
                                        'minLength': 11,
                                        'type': 'string'},
                          'optionSetAttribute': {'type': 'boolean'},
                          'organisationUnitAttribute': {'type': 'boolean'},
                          'organisationUnitGroupAttribute': {'type': 'boolean'},
                          'organisationUnitGroupSetAttribute': {'type': 'boolean'},
                          'programAttribute': {'type': 'boolean'},
                          'programIndicatorAttribute': {'type': 'boolean'},
                          'programStageAttribute': {'type': 'boolean'},
                          'publicAccess': {'example': 'rw------',
                                           'format': 'access',
                                           'maxLength': 8,
                                           'minLength': 8,
                                           'type': 'string'},
                          'sectionAttribute': {'type': 'boolean'},
                          'shortName': {'format': 'general',
                                        'maxLength': 50,
                                        'minLength': 1,
                                        'type': 'string'},
                          'sortOrder': {'association': 'true',
                                        'format': 'integer',
                                        'maxLength': 255,
                                        'minLength': 1,
                                        'type': 'string'},
                          'sqlViewAttribute': {'type': 'boolean'},
                          'trackedEntityAttributeAttribute': {'type': 'boolean'},
                          'trackedEntityTypeAttribute': {'type': 'boolean'},
                          'translation': {'items': {'maxProperties': 2147483647,
                                                    'minProperties': 0,
                                                    'properties': {}},
                                          'maxItems': 2147483647,
                                          'minItems': 0,
                                          'readOnly': False,
                                          'type': 'array'},
                          'translations': {'maxItems': 2147483647,
                                           'minItems': 0,
                                           'type': 'array'},
                          'unique': {'type': 'boolean'},
                          'user': {'association': 'true',
                                   'format': 'uid',
                                   'maxLength': 11,
                                   'minLength': 11,
                                   'type': 'string'},
                          'userAccess': {'items': {'maxProperties': 2147483647,
                                                   'minProperties': 0,
                                                   'properties': {'access': {'format': 'access',
                                                                             'maxLength': 8,
                                                                             'minLength': 8,
                                                                             'readOnly': False,
                                                                             'type': 'string'},
                                                                  'displayName': {'readOnly': True,
                                                                                  'type': 'string'},
                                                                  'id': {'maxLength': 255,
                                                                         'minLength': 0,
                                                                         'readOnly': False,
                                                                         'type': 'string'},
                                                                  'userUid': {'readOnly': True,
                                                                              'type': 'string'}},
                                                   'required': []},
                                         'maxItems': 2147483647,
                                         'minItems': 0,
                                         'readOnly': False,
                                         'type': 'array'},
                          'userAccesses': {'maxItems': 2147483647,
                                           'minItems': 0,
                                           'type': 'array'},
                          'userAttribute': {'type': 'boolean'},
                          'userGroupAccess': {'items': {'maxProperties': 2147483647,
                                                        'minProperties': 0,
                                                        'properties': {'access': {'format': 'access',
                                                                                  'maxLength': 8,
                                                                                  'minLength': 8,
                                                                                  'readOnly': False,
                                                                                  'type': 'string'},
                                                                       'displayName': {'readOnly': True,
                                                                                       'type': 'string'},
                                                                       'id': {'maxLength': 255,
                                                                              'minLength': 0,
                                                                              'readOnly': False,
                                                                              'type': 'string'},
                                                                       'userGroupUid': {'readOnly': True,
                                                                                        'type': 'string'}},
                                                        'required': []},
                                              'maxItems': 2147483647,
                                              'minItems': 0,
                                              'readOnly': False,
                                              'type': 'array'},
                          'userGroupAccesses': {'maxItems': 2147483647,
                                                'minItems': 0,
                                                'type': 'array'},
                          'userGroupAttribute': {'type': 'boolean'},
                          'validationRuleAttribute': {'type': 'boolean'},
                          'validationRuleGroupAttribute': {'type': 'boolean'},
                          'valueType': {'enum': ['INTEGER_NEGATIVE',
                                                 'BOOLEAN',
                                                 'IMAGE',
                                                 'DATETIME',
                                                 'COORDINATE',
                                                 'LETTER',
                                                 'NUMBER',
                                                 'PERCENTAGE',
                                                 'EMAIL',
                                                 'URL',
                                                 'TEXT',
                                                 'PHONE_NUMBER',
                                                 'TRACKER_ASSOCIATE',
                                                 'TIME',
                                                 'TRUE_ONLY',
                                                 'INTEGER_POSITIVE',
                                                 'UNIT_INTERVAL',
                                                 'USERNAME',
                                                 'INTEGER',
                                                 'INTEGER_ZERO_OR_POSITIVE',
                                                 'ORGANISATION_UNIT',
                                                 'FILE_RESOURCE',
                                                 'LONG_TEXT',
                                                 'DATE',
                                                 'AGE'],
                                        'example': 'TEXT',
                                        'format': 'enum',
                                        'type': 'string'}},
           'required': ['name', 'valueType'],
           'type': 'object',
           'x-status-dhis2': 'template'},
 'maxItems': 1.7976931348623157e+308,
 'minItems': 0.0,
 'readOnly': False,
 'type': 'array'}




in_schema_json = json.dumps(in_schema)
#print(in_schema_json)

sins = pformat(in_schema)

dins = literal_eval(sins)
pprint(dins)


builder.add_schema(dins)

out_schema = builder.to_schema()

pprint(out_schema)
